In [1]:
import torch

*Tensor is a number, vector matrix or any n-dimentional array*

In [2]:
t1 = torch.tensor(4.)

*4. is a shorthand for 4.0. It is used to indicate to PyTorch that we want to create a floating point number. Can be checked by dtype attribute of tensor*

In [4]:
t1.dtype

torch.float32

In [6]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [7]:
# Matrix
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
# 3-dimensional array
t4 = torch.tensor([[[11, 12, 13], [13, 14, 15]], [[15, 16, 17], [17, 18, 19]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [9]:
print (t1.shape)
print (t2.shape)
print (t3.shape)
print (t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


***Tensor operations and gradients***

In [10]:
# Creating tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [11]:
# Arithmetic operations
y = w * x + b

In [13]:
y

tensor(17., grad_fn=<AddBackward0>)

*y is a tensor with value 3 * 4 + 5 = 17. Attribute require_grad is set to True because we want to compute derivative of y w.r.t w and b. For computing derivative we use .backward() method*

In [14]:
y.backward()

C:\Users\rhz_3\anaconda3\lib\site-packages\torch\autograd\__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


In [15]:
# Displaying Gradients
print ('dy/dx: ', x.grad)
print ('dy/dw: ', w.grad)
print ('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


***Interoperability with Numpy***

*From numpy, we can use Matplotlib for plotting and visualization. OpenCV for image and video processing. Pandas for file I/O and data analysis*

In [17]:
import numpy as np

In [18]:
# Creating numpy array
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [20]:
# Converting numpy array to torch tensor
y = torch.from_numpy(x) # uses the same space in the memory
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [21]:
# Converting numpy array to toch tensor second way
y = torch.tensor(x) # creates a copy and stores y in different space in memory
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [22]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [23]:
# Converting torch tensor to numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

<h2>Linear Regression</h2>

In [24]:
# Creating Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [25]:
# Creating Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [26]:
# Converting numpy arrays to torch tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print (inputs)
print (targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [27]:
# Filling weights and bias with random values first
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True) # torch.randn picks mostly values from -1 to 1, with normal or gaussian distribution
                                       # with mean 0 and standard deviation of 1
print (w)
print (b)

tensor([[-0.6227, -0.1633, -1.0429],
        [ 1.7649, -0.1940, -1.3155]], requires_grad=True)
tensor([0.5435, 0.8383], requires_grad=True)


In [28]:
# defining model
def model(x):
    return x @ w.t() + b # @ repsents matrix multiplication in PyTorch and .t method transposes a tensor

In [29]:
# Getting predictions
preds = model(inputs)
print (preds)

tensor([[-100.7018,   60.1104],
        [-137.2414,   60.1788],
        [-136.0049,   52.0863],
        [-108.5840,  123.8425],
        [-131.1055,   11.9055]], grad_fn=<AddBackward0>)


In [30]:
# Printing Targets for comparison
print (targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


***Loss Function***

In [31]:
# Mean Square Error (MSE) loss function
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel() # .numel method returns the number of elements

In [32]:
# Comput loss
loss = mse(preds, targets)
print (loss)

tensor(23639.1875, grad_fn=<DivBackward0>)


***Computing Gradients***

In [33]:
# computing gradients with backpropagation
loss.backward()

In [34]:
print (w)
print (w.grad)

tensor([[-0.6227, -0.1633, -1.0429],
        [ 1.7649, -0.1940, -1.3155]], requires_grad=True)
tensor([[-16591.4941, -18392.8320, -11342.9805],
        [ -2001.5486,  -4328.8291,  -2402.8489]])


In [35]:
print (b)
print (b.grad)

tensor([0.5435, 0.8383], requires_grad=True)
tensor([-198.9275,  -30.3753])


In [36]:
# resetting gradients to zero to perform gradient descent
w.grad.zero_()
b.grad.zero_()
print (w.grad)
print (b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


***Adjust weights and biases using gradient descent***

*1) Generate predictions*
*2) Calculate Loss*
*3) Compute gradients w.r.t the weights and biases*
*4) Adjust the weights by subtracting a small quantity proportional to the gradient*
*5) Reset the gradients to zero*

In [37]:
# Generate predictions
preds = model(inputs)
print (preds)

tensor([[-100.7018,   60.1104],
        [-137.2414,   60.1788],
        [-136.0049,   52.0863],
        [-108.5840,  123.8425],
        [-131.1055,   11.9055]], grad_fn=<AddBackward0>)


In [38]:
# Calculate loss
loss = mse(preds, targets)
print (loss)

tensor(23639.1875, grad_fn=<DivBackward0>)


In [39]:
# Compute gradients
loss.backward()
print (w.grad)
print (b.grad)

tensor([[-16591.4941, -18392.8320, -11342.9805],
        [ -2001.5486,  -4328.8291,  -2402.8489]])
tensor([-198.9275,  -30.3753])


In [40]:
# Adjusting weights and reseting gradients
with torch.no_grad(): #.no_grad() ensures pytorch doesn't track, calculate or modify gradients while update
    w -= w.grad * 1e-5  #1e-5 is the learning rate
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [41]:
print (w)
print (b)

tensor([[-0.4568,  0.0206, -0.9295],
        [ 1.7849, -0.1507, -1.2915]], requires_grad=True)
tensor([0.5455, 0.8386], requires_grad=True)


In [42]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(16619.3105, grad_fn=<DivBackward0>)


***Training for multiple epochs***

In [43]:
# 100 epochs training
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [44]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(756.3623, grad_fn=<DivBackward0>)


In [46]:
print (targets)
print (preds)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[ 60.7257,  81.8754],
        [ 76.9722,  95.0812],
        [124.8760, 127.0774],
        [ 40.4682, 102.0778],
        [ 81.6095,  71.6116]], grad_fn=<AddBackward0>)
