In [1]:
import torch

*Tensor is a number, vector matrix or any n-dimentional array*

In [2]:
t1 = torch.tensor(4.)

*4. is a shorthand for 4.0. It is used to indicate to PyTorch that we want to create a floating point number. Can be checked by dtype attribute of tensor*

In [4]:
t1.dtype

torch.float32

In [6]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [7]:
# Matrix
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
# 3-dimensional array
t4 = torch.tensor([[[11, 12, 13], [13, 14, 15]], [[15, 16, 17], [17, 18, 19]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [9]:
print (t1.shape)
print (t2.shape)
print (t3.shape)
print (t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


***Tensor operations and gradients***

In [10]:
# Creating tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [11]:
# Arithmetic operations
y = w * x + b

In [13]:
y

tensor(17., grad_fn=<AddBackward0>)

*y is a tensor with value 3 * 4 + 5 = 17. Attribute require_grad is set to True because we want to compute derivative of y w.r.t w and b. For computing derivative we use .backward() method*

In [14]:
y.backward()

C:\Users\rhz_3\anaconda3\lib\site-packages\torch\autograd\__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


In [15]:
# Displaying Gradients
print ('dy/dx: ', x.grad)
print ('dy/dw: ', w.grad)
print ('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


***Interoperability with Numpy***

*From numpy, we can use Matplotlib for plotting and visualization. OpenCV for image and video processing. Pandas for file I/O and data analysis*

In [17]:
import numpy as np

In [18]:
# Creating numpy array
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [20]:
# Converting numpy array to torch tensor
y = torch.from_numpy(x) # uses the same space in the memory
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [21]:
# Converting numpy array to toch tensor second way
y = torch.tensor(x) # creates a copy and stores y in different space in memory
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [22]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [23]:
# Converting torch tensor to numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])